reset;
option solver gurobi;
option display_eps 1e-05;
option omit_zero_rows 1;
model C:\Saayuj\IITBombay\Academic\Sem6\ME308\Codes\AMPL\multidrone_multipackage.mod;
data C:\Saayuj\IITBombay\Academic\Sem6\ME308\Codes\AMPL\multidrone_multipackage.dat;
solve;
display {t in 1..time}: {n in 1..number_of_drones, i in 1..grid_size, j in 1..grid_size} nodes[n, i, j, t] > nodes_mm.txt;
#display flag > flag.txt;
